DocWorks for wix-bookings-backend - 17 changes detected, but 9 issue detected changes: Service wix-bookings-backend message Attendance was removed Service wix-bookings-backend message BusinessLocation was removed Service wix-bookings-backend message BusinessSchedule was removed Service wix-bookings-backend message ContactDetailsInfo was removed Service wix-bookings-backend message CustomFormField was removed Service wix-bookings-backend message CustomFormFieldInfo was removed Service wix-bookings-backend message Form was removed Service wix-bookings-backend message Image was removed Service wix-bookings-backend message ImageInfo was removed Service wix-bookings-backend message PaymentSelectionInfo was removed Service wix-bookings-backend message PricingPlan was removed Service wix-bookings-backend message PricingPlanDetails was removed Service wix-bookings-backend message RateInfo was removed Service wix-bookings-backend message SpecialHourPeriod was removed Service wix-bookings-backend message TimePeriod was removed Service wix-bookings-backend message TimePeriod_38785543152 was removed Service wix-bookings-backend message WixPayDetails was removed
issues:
Operation eq has an unknown param type * (ResourceCatalogQueryBuilder.js (47))
Operation eq has an unknown param type * (WixBookingsQueryBuilder.js (48))
Operation createResource has an unknown param type wix-bookings-backend.resources.Resource_13052683855:createResource (resources.js (18))
Operation createResource has an unknown return type wix-bookings-backend.Resource_23420910898:createResource (resources.js (18))
Message Address is defined two or more times (address.js (4), shared-autogen.js (1148))
Message StreetAddress is defined two or more times (address.js (20), shared-autogen.js (1218))
Message AddressLocation is defined two or more times (address.js (29), shared-autogen.js (1202, 1210))
ERROR: The @snippet tag - file 'velo-docs/examples/createResourceBusinessHours.es6' not found. File: resources.js li ...